# (generated with --quick)

from typing import Any

MPI: Any
np: module
torch: module

def _get_flat_params_or_grads(network, mode = ...) -> Any: ...
def _set_flat_params_or_grads(network, flat_params, mode = ...) -> None: ...
def sync_grads(network) -> None: ...
def sync_networks(network) -> None: ...
